actor/urls.py
from django.urls import path
from actor import views

app_name = "actor"
urlpatterns = [
    path("list/", views.actor_list, name="list"),
    path("detail/<int:pk>/", views.actor_detail, name="detail"),
    path("create-actor/", views.create_actor, name="create"),
    path("update-actor/<int:pk>/", views.update_actor, name="update"),
    path("delete-actor/<int:pk>/", views.delete_actor, name="delete"),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls")),
    path("actor/", include("actor.urls", namespace="actor")),
    path("users/", include("users.urls", namespace="user"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

actor/models.py
from django.db import models
from django.urls import reverse
from helpers.choices import AwardsChoices
from movie.models import Movie


class Actor(models.Model):

    first_name = models.CharField(max_length=155)
    last_name = models.CharField(max_length=155)
    age = models.PositiveIntegerField()
    awards = models.IntegerField(choices=AwardsChoices.choices,
                                 null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="actor/images")
    movies = models.ManyToManyField(Movie, related_name="actor")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("actor:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

actor/forms.py
from django import forms

from actor.models import Actor


class ActorForm(forms.ModelForm):

    class Meta:
        model = Actor
        fields = ("first_name", "last_name",
                  "age", "awards", "image", "movies")

actor/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from actor.forms import ActorForm
from actor.models import Actor


def actor_list(request):
    actors = Actor.objects.order_by("-id")
    paginator = Paginator(actors, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "actor/list_actor.html",
                  context={"page_obj": page_obj})


def actor_detail(request, pk):
    actor = get_object_or_404(Actor, pk=pk)
    return render(request, "actor/detail_actor.html",
                  {"actor": actor})


@login_required
def create_actor(request):
    form = ActorForm()
    if request.method == "POST":
        form = ActorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "successfully creating actor instance")
            return redirect("home")
    return render(request, "actor/create_actor.html", {"form": form})


@login_required
def update_actor(request, pk):
    actor = get_object_or_404(Actor, pk=pk)
    form = ActorForm(instance=actor)
    if request.method == "POST":
        form = ActorForm(request.POST, request.FILES, instance=actor)
        if form.is_valid():
            form.save()
            messages.error(request, "Actor object updated successfully")
            messages.success(request, "Just testing both cases")
            return redirect("actor:list")
    return render(request, "actor/update_actor.html", {"form": form})


@login_required
def delete_actor(request, pk):
    actor = get_object_or_404(Actor, pk=pk)
    if request.method == "POST":
        actor.delete()
        messages.info(request, "Actor deleted successfully")
        return redirect("actor:list")
    return render(request, "actor/delete_actor.html", {"actor": actor})

templates/actor/create_actor.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-secondary btn-lg btn-block">Create</button>
        </form>
    </div>

{% endblock %}

templates/actor/delete_actor.html
{% extends "base.html" %}


{% block content %}
    <div class="container">
    <h2>Are you sure you want to delete {{ actor.first_name }} {{ actor.last_name }}</h2>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">DELETE</button>
            <a href="{{ actor.get_absolute_url }}">go back</a>
        </form>
    </div>

{% endblock %}

templates/actor/detail_actor.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <a href="{% url 'actor:update' actor.pk %}" class="btn btn-success">UPDATE</a>
        <a href="{% url 'actor:delete' actor.pk %}" class="btn btn-danger">DELETE</a>
    </div>
{% endblock %}

templates/actor/list_actor.html
{% extends 'base.html' %}


{% block content %}

<div class="card-group">
    {% for actor in page_obj %}
        <div class="card">
        <img class="card-img-top" src="{% if actor.image %}{{ actor.image.url }}{% endif %}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ actor.first_name }} {{ actor.last_name }}</h5>
            <p class="card-text">{{ actor.age }}</p>
            <p class="card-text">{{ actor.awards }}</p>
            <p class="card-text">Movie counts {{ actor.movies.count }}</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
        <a href="{{ actor.get_absolute_url }}" class="btn btn-success">Actor Detail</a>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/actor/update_actor.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">UPDATE</button>
        </form>

    </div>

{% endblock %}