actor/urls.py
from django.urls import path
from actor import views

app_name = "actor"
urlpatterns = [
    path("list/", views.actor_list, name="list"),
    path("detail/<int:pk>/", views.actor_detail, name="detail"),
    path("create-actor/", views.create_actor, name="create"),
    path("update-actor/<int:pk>/", views.update_actor, name="update"),
    path("delete-actor/<int:pk>/", views.delete_actor, name="delete"),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls")),
    path("actor/", include("actor.urls", namespace="actor")),
    path("users/", include("users.urls", namespace="user"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

users/urls.py
from django.urls import path
from users import views
from users.views import DeleteUserView

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login_user"),
    path("log-out/", views.logout_user, name="log_out_user"),
    path("profiles/list", views.ProfileListView.as_view(), name="profile-list"),
    path("profile/<int:id>/", views.ProfileView.as_view(), name="profile"),
    path("profile/update/<int:id>", views.UpdateProfileView.as_view(), name="update_profile"),
    path("profile/delete/<int:id>/", DeleteUserView.as_view(), name="user_delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Default{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Movie Website</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
             aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Movies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'actor:list' %}">Actors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about_us' %}">About US</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'add_movie' %}">Add Movie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'actor:create' %}">Add Actor</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Categories
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            {% for category in categories %}
                                <li><a class="dropdown-item"
                                       href="{% url 'shnorhavor_amanor' %}?category={{ category.category_name }}">{{ category.category_name }}</a>
                                </li>
                            {% endfor %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            {% if not request.user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'user:register' %}">Register</a></li>
                                <li><a class="dropdown-item" href="{% url 'user:login_user' %}">Login</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'user:profile-list' %}">Profiles</a></li>
                                <li><a class="dropdown-item" href="{% url 'user:profile' request.user.pk %}">Own profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'user:log_out_user' %}">LogOut</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
                <form class="d-flex mt-3" role="search" method="get">
                    <input class="form-control me-2" name="search_data" type="search" placeholder="Search"
                           aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>

<br>
<br>
<br>

{% include "layouts/messages.html" %}
{% block content %}

{% endblock %}

{% include 'layouts/pagination.html' %}

</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</html>