actor/urls.py
from django.urls import path
from actor import views

app_name = "actor"
urlpatterns = [
    path("list/", views.actor_list, name="list"),
    path("detail/<int:pk>/", views.actor_detail, name="detail"),
    path("create-actor/", views.create_actor, name="create"),
    path("update-actor/<int:pk>/", views.update_actor, name="update"),
    path("delete-actor/<int:pk>/", views.delete_actor, name="delete"),
]

first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movie.urls")),
    path("actor/", include("actor.urls", namespace="actor")),
    path("users/", include("users.urls", namespace="user"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

users/urls.py
from django.urls import path
from users import views
from users.views import DeleteUserView

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login_user"),
    path("log-out/", views.logout_user, name="log_out_user"),
    path("profiles/list", views.ProfileListView.as_view(), name="profile-list"),
    path("profile/<int:id>/", views.ProfileView.as_view(), name="profile"),
    path("profile/update/<int:id>", views.UpdateProfileView.as_view(), name="update_profile"),
    path("profile/delete/<int:id>/", DeleteUserView.as_view(), name="user_delete"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="photo/", blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    country = CountryField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}"


@receiver(post_save, sender=User)
def post_save_user(instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from phonenumber_field.formfields import PhoneNumberField
from django_countries.fields import CountryField


class RegisterForm(UserCreationForm):

    phone_number = PhoneNumberField()
    country = CountryField().formfield()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].required = True

    class Meta(UserCreationForm.Meta):
        fields = ("username", "email", "phone_number",
                  "country", "password1", "password2")


class LoginForm(forms.Form):
    username = forms.CharField(max_length=155)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        fields = ("username", "password")


class DeleteForm(forms.Form):

    class Meta:
        fields = tuple()

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.base import TemplateResponseMixin, ContextMixin, View
from django.views.generic.edit import FormMixin

from users.forms import RegisterForm, LoginForm, DeleteForm
from users.mixins import OwnUserMixin


def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            instance = form.save()
            instance.profile.phone_number = form.cleaned_data["phone_number"]
            instance.profile.country = form.cleaned_data["country"]
            instance.profile.save()
            return redirect("home")
    return render(request, "user/registration.html",
                  {"form": form})


def login_user(request):
    form = LoginForm()
    next_url = request.GET.get("next")
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = get_object_or_404(User, username=form.cleaned_data["username"])
            login(request, user)
            if next_url:
                return redirect(next_url)
            return redirect("home")
    return render(request, "user/login.html", {"form": form})


def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("home")


class ProfileListView(LoginRequiredMixin, ListView):
    queryset = User.objects.filter(is_superuser=False)
    template_name = "user/user_list.html"
    paginate_by = 2


class ProfileView(FormMixin, LoginRequiredMixin, DetailView):
    template_name = "user/profile.html"
    model = User
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Profile"
        return context

    def get_form(self, form_class=None):
        return DeleteForm()

    def get_success_url(self):
        messages.info(self.request, "YOur account has been deleted")
        return reverse_lazy("home")

    def form_valid(self, form):
        self.object.delete()
        return super().form_valid(form)


class UpdateProfileView(OwnUserMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = "user/profile_update.html"
    fields = ("first_name", "last_name", "email", "username")
    pk_url_kwarg = 'id'

    def get_success_url(self):
        messages.success(self.request, "Profile instance saved successfully")
        return reverse_lazy("user:profile", args=(self.object.pk,))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "UPDATE|PROFILE"
        return context


class DeleteUserView(OwnUserMixin, LoginRequiredMixin, DeleteView):
    model = User
    template_name = "user/delete_account.html"
    pk_url_kwarg = 'id'

    def get_success_url(self):
        messages.warning(self.request, "Your Account has been deleted")
        return reverse_lazy("home")

templates/user/delete_account.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <h1>Are you sure you want to delete this wonderful account</h1>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">DELETE</button>
        </form>
        <a href="{% url 'user:profile' request.user.pk %}" class="btn btn-primary">Go To Profile</a>
    </div>

{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary w-100">Login</button>
        </form>
    </div>


{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1>Profile Page</h1>
        {{ title }}

        {{ object }}<br>
        {{ object.first_name }}<br>
        {{ object.last_name }}<br>
        {{ object.email }}
        <button class="btn btn-primary"><a href="{% url 'user:update_profile' object.pk %}" style="color: #1b1b1b">Update
            Profile</a></button>
        <button class="btn btn-danger"><a href="{% url 'user:user_delete' object.pk %}" style="color: #1b1b1b">Delete
            Profile</a></button>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger w-100">DELETE</button>
        </form>

    </div>
{% endblock %}

templates/user/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Update profile</button>
    </form>
</div>

{% endblock %}

templates/user/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary w-100">Register</button>
        </form>
    </div>


{% endblock %}

templates/user/user_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    {% for user in object_list %}
        <h1><a href="{% url 'user:profile' user.pk %}">{{ user.username }}</a></h1>
    {% endfor %}
    </div>

{% endblock %}